### ISSUE TITLE
Not working on variation products

### ISSUE THREAD

**Issue by Nodws** [pkolomeitsev/woo-exchange-rate#7]
only works on simple products, products with variations remain the same when user is logged in

**Comment by pkolomeitsev** [comment]
Hi @Nodws,
New version 17.4 released. It's available on WordPress Store.
Please check, your issue should be fixed.

**Comment by Nodws** [comment]
Sorry didnt work, here is a screenshot
When user is logged in it ignores all the rates calculation routine
If I force the rate conversion in wc_price() it works but breaks normal products 
![image](https://cloud.githubusercontent.com/assets/3076134/25342984/eef5f51c-28ca-11e7-8bd8-fc3935c13c08.png)

**Comment by Nodws** [comment]
AHA! Found the culprit
Disabled "Customer Specific Pricing for WooCommerce" now prices show OK
seems they are not compatible,

**Comment by pkolomeitsev** [comment]
@Nodws could you please send me a link to this plugin?

**Comment by Nodws** [comment]
Notified them, they fixed it already, all works now 
https://wisdmlabs.com/woocommerce-user-specific-pricing-extension/

**Comment by Nodws** [comment]
Weird I think the price cache cleared and now the simple products are not being converted to rate, I've disabled all plugins but still no go.

Rolled back to previous version, disabled the "Customer Specific Pricing"  plugin, and that works fine >.<

**Comment by pkolomeitsev** [comment]
Well, soon, i'll check your plugin and try to reproduce.

**Comment by Nodws** [comment]
I gonna deliver  this site as  is, client already satisfied  :P 
but I can email you the plugin if you want contact[at]nodws.com

**Comment by pkolomeitsev** [comment]
I've tested with https://wordpress.org/plugins/customer-specific-pricing-lite/ works well, but it doesn't seems to support customer prices for variation products. I don't really want to buy every WP plugin to fix compatibility issues, sorry...
Anyway @Nodws thank you for your reply!

**Comment by Nodws** [comment]
Yeah no problem ;)
